### ISSUE TITLE
eval outline doesn't work on some corner cases

### ISSUE THREAD

**Issue by et2010** [abo-abo/lpy#10]
eval doesn't work on following outline

```
# * Title 1

mylist = []
mylist.append([
    'a',
    'b',
    'c'
])
```
Here is the traceback:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/jw/work/examples/debug.py", line 5
    ’c’
      ^
SyntaxError: invalid syntax
  File "<stdin>", line 1
    ])
    ^
SyntaxError: invalid syntax
```

But it does work when reformatting the code as follows:

```
# * Title 1

mylist = []
mylist.append(['a', 'b', 'c'])
```

**Comment by abo-abo** [comment]
Thanks, please test. See the commit msg for details if you're interested.
