### ISSUE TITLE
name 'lp' is not defined on pspecial-lispy-eval

### ISSUE THREAD

**Issue by joshcho** [abo-abo/lpy#39]
When calling pspecial-lispy-eval in certain places (variable assignment within functions), I get the following:
```
NameError: name ’lp’ is not defined
Traceback (most recent call last):
  File "<string>", line 19, in __PYTHON_EL_eval
  File "/home/usr/try.py", line 2, in <module>
    x = 5
```

Interestingly enough, the following fixes it:
```
(define-key lpy-mode-map (kbd "e") (lambda ()
                                       (interactive)
                                       (pspecial-lispy-eval)))
```
which I don't really understand why.

**Comment by fanshi1028** [comment]
> When calling pspecial-lispy-eval in certain places (variable assignment within functions), I get the following:
> 
> ```
> NameError: name ’lp’ is not defined
> Traceback (most recent call last):
>   File "<string>", line 19, in __PYTHON_EL_eval
>   File "/home/usr/try.py", line 2, in <module>
>     x = 5
> ```
> 
> Interestingly enough, the following fixes it:
> 
> ```
> (define-key lpy-mode-map (kbd "e") (lambda ()
>                                        (interactive)
>                                        (pspecial-lispy-eval)))
> ```
> 
> which I don't really understand why.

Check if lispy--python-middleware-loaded-p  is t.
If not, run (lispy--python-middleware-load).
This solves the issues for me, hope it helps.
